from PyQt5 import QtCore, QtGui, QtWidgets


class AccountEditWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 473)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(41)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.GenerateButton = QtWidgets.QPushButton(self.centralwidget)
        self.GenerateButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GenerateButton.sizePolicy().hasHeightForWidth())
        self.GenerateButton.setSizePolicy(sizePolicy)
        self.GenerateButton.setObjectName("GenerateButton")
        self.horizontalLayout_2.addWidget(self.GenerateButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 3, 1, 1)
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 0, 1, 4)
        self.emailLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.emailLabel.setFont(font)
        self.emailLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout.addWidget(self.emailLabel, 3, 0, 1, 1)
        self.urlLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.urlLabel.setFont(font)
        self.urlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.urlLabel.setObjectName("urlLabel")
        self.gridLayout.addWidget(self.urlLabel, 5, 0, 1, 1)
        self.URLlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.URLlineEdit.setFont(font)
        self.URLlineEdit.setObjectName("URLlineEdit")
        self.gridLayout.addWidget(self.URLlineEdit, 5, 2, 1, 1)
        self.Passwordlabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Passwordlabel.setFont(font)
        self.Passwordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Passwordlabel.setObjectName("Passwordlabel")
        self.gridLayout.addWidget(self.Passwordlabel, 4, 0, 1, 1)
        self.Taglabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Taglabel.setFont(font)
        self.Taglabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Taglabel.setObjectName("Taglabel")
        self.gridLayout.addWidget(self.Taglabel, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveButton.sizePolicy().hasHeightForWidth())
        self.SaveButton.setSizePolicy(sizePolicy)
        self.SaveButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SaveButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Earth\\Desktop\\passwordManager\\Main\\styles\\../Icons/plus-16.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveButton.setIcon(icon)
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)
        self.openUrlButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openUrlButton.sizePolicy().hasHeightForWidth())
        self.openUrlButton.setSizePolicy(sizePolicy)
        self.openUrlButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openUrlButton.setFont(font)
        self.openUrlButton.setObjectName("openUrlButton")
        self.horizontalLayout.addWidget(self.openUrlButton)
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExitButton.sizePolicy().hasHeightForWidth())
        self.ExitButton.setSizePolicy(sizePolicy)
        self.ExitButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ExitButton.setFont(font)
        self.ExitButton.setObjectName("ExitButton")
        self.horizontalLayout.addWidget(self.ExitButton)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 4)
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 2, 0, 1, 1)
        self.tagLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tagLineEdit.setFont(font)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.gridLayout.addWidget(self.tagLineEdit, 1, 2, 1, 1)
        self.userNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userNameLineEdit.setFont(font)
        self.userNameLineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.userNameLineEdit, 2, 2, 1, 1)
        self.emailLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.gridLayout.addWidget(self.emailLineEdit, 3, 2, 1, 1)
        self.passwordLintEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordLintEdit.setFont(font)
        self.passwordLintEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLintEdit.setObjectName("passwordLintEdit")
        self.gridLayout.addWidget(self.passwordLintEdit, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        

        # Add Manually
        self.GenerateButton.clicked.connect(self.copyPassword)
        self.checkBox.stateChanged.connect(self.togglePassword)
        # make Tag read only
        self.tagLineEdit.setReadOnly(True)
        # place demo text in tagLineEdit
        self.tagLineEdit.setText("Demo")
        self.openUrlButton.clicked.connect(self.openUrl)
        # demo url for openUrlButton
        self.URLlineEdit.setText("https://www.google.com")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    # Buttons -> Generate
    def genPassword(self):
        import string,random

        apl = string.ascii_letters + string.digits + string.digits
        aplList = []
        aplList.extend(apl)
        random.shuffle(aplList)

        genPassWord = "".join(aplList[:16])
        self.passwordLintEdit.setText(genPassWord)
    
        # checkBox -> ShowPassword
    def togglePassword(self):
        if self.checkBox.isChecked():
            self.passwordLintEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        else:
            self.passwordLintEdit.setEchoMode(QtWidgets.QLineEdit.Password)

    # open url in browser
    def openUrl(self):
        import webbrowser
        if self.URLlineEdit.text().startswith(("https://","http://")):

            webbrowser.open(url=self.URLlineEdit.text())
        else:
            webbrowser.open(url=f"http://{self.URLlineEdit.text()}")
    # copy password to clipboard
    def copyPassword(self):
        QtWidgets.QApplication.clipboard().setText(self.passwordLintEdit.text())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "Show"))
        # self.GenerateButton.setText(_translate("MainWindow", "Generate"))
        self.GenerateButton.setText(_translate("MainWindow", "Copy"))
        self.TitleLabel.setText(_translate("MainWindow", "Edit Password"))
        self.emailLabel.setText(_translate("MainWindow", "Email"))
        self.urlLabel.setText(_translate("MainWindow", "URL"))
        self.Passwordlabel.setText(_translate("MainWindow", "Password"))
        self.Taglabel.setText(_translate("MainWindow", "Tag/Label"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.openUrlButton.setText(_translate("MainWindow", "Open URL"))
        self.ExitButton.setText(_translate("MainWindow", "Exit"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = AccountEditWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
